{"uuid": "0f9a54e3-dca6-49bb-92b6-1a7f73b464a9", "children": ["cae22a1d-45d4-4358-985b-cc301901c77a"], "befores": [{"name": "login", "status": "broken", "statusDetails": {"message": "requests.exceptions.ProxyError: HTTPSConnectionPool(host='api.wy56.com', port=443): Max retries exceeded with url: /test/wms-api/system/login (Caused by ProxyError('Your proxy appears to only use HTTP and not HTTPS, try changing your proxy URL to be HTTP. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#https-proxy-error-http-proxy', SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1108)'))))\n", "trace": "  File \"D:\\Python3\\Proj\\venv\\lib\\site-packages\\pluggy\\_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"D:\\Python3\\Proj\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 1126, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"D:\\Python3\\Proj\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 932, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"D:\\Python3\\Proj\\testcases\\conftest.py\", line 20, in login\n    rep = RequestUtil().send_request(method, baseinfo[\"base\"][\"login_url\"], data, post_type)\n  File \"D:\\Python3\\Proj\\common\\request_util.py\", line 18, in send_request\n    rep = RequestUtil.session.request(method, url=url, data=data,**kwargs)\n  File \"D:\\Python3\\Proj\\venv\\lib\\site-packages\\requests\\sessions.py\", line 529, in request\n    resp = self.send(prep, **send_kwargs)\n  File \"D:\\Python3\\Proj\\venv\\lib\\site-packages\\requests\\sessions.py\", line 645, in send\n    r = adapter.send(request, **kwargs)\n  File \"D:\\Python3\\Proj\\venv\\lib\\site-packages\\requests\\adapters.py\", line 513, in send\n    raise ProxyError(e, request=request)\n"}, "start": 1646189336290, "stop": 1646189336309}], "start": 1646189336290, "stop": 1646189337242}